POST  http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1hc2EiLCJpZCI6IjYwNGI4NTA2YTJlYjk1NDEzMGMyM2ZkOCIsImlhdCI6MTYxNTU2NDg4MH0.CEAqZPOq1jfZNzVKOoiDO-YiZTXsn9GjJVZoL_GF6mU

{
  "title": "Masan kastike 2",
  "author": "Ilpo Jokinen",
  "url": "http://www.ilpojokinenfoodblog.me",
  "likes": 100
}