POST http://localhost:3001/api/notes
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1sdXVra2FpIiwiaWQiOiI2MDNhMzM4MzJlZGJiZDA3NjgyYTQ2NGEiLCJpYXQiOjE2MTU1MzY3MTR9.G3G_52_ZEuzpLHxWXJJSIpUnIIJ_vKoAYsJYOQQpWf0

{
  "content": "Matti's last note",
  "important": false
}